### get all users
GET http://localhost:3000/users


### register new user
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "username1@gmail.com",
  "username": "username1",
  "password": "password1",
  "role": "admin"
}


### login user
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "username1",
  "password": "password1"
}


### get admin data (⚠️ update jwtToken !!)
GET http://localhost:3000/admin
Cookie: jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjOWMzNGE5LTA1ZmMtNDdhOS04NzU3LWY5ZjdkZjEzMDUxMiIsImlhdCI6MTY5NDUzNTM4NiwibmJmIjoxNjk0NTM1NDA2LCJleHAiOjE2OTQ1MzU1MDZ9.h2z9FtludHp99q9CtUmjwAdJQE6hr6bGYLmdabKYCt8


### logout user (⚠️ update jwtToken !!)
DELETE http://localhost:3000/logout
Cookie: jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjOWMzNGE5LTA1ZmMtNDdhOS04NzU3LWY5ZjdkZjEzMDUxMiIsImlhdCI6MTY5NDUzNTM4NiwibmJmIjoxNjk0NTM1NDA2LCJleHAiOjE2OTQ1MzU1MDZ9.h2z9FtludHp99q9CtUmjwAdJQE6hr6bGYLmdabKYCt8


### delete user account (⚠️ update jwtToken !!)
DELETE http://localhost:3000/deleteAccount
Cookie: jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjOWMzNGE5LTA1ZmMtNDdhOS04NzU3LWY5ZjdkZjEzMDUxMiIsImlhdCI6MTY5NDUzNTM4NiwibmJmIjoxNjk0NTM1NDA2LCJleHAiOjE2OTQ1MzU1MDZ9.h2z9FtludHp99q9CtUmjwAdJQE6hr6bGYLmdabKYCt8